# Generated by Django 5.2.1 on 2025-05-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('duration', models.DateTimeField()),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bulletin',
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_registry',
            },
        ),
        migrations.CreateModel(
            name='CancelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('reason_detail', models.TextField(null=True)),
                ('executed_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cancel_requirement',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.bulletin')),
            ],
            options={
                'db_table': 'interaction',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=124)),
                ('avatar', models.CharField(max_length=124)),
                ('email', models.CharField(max_length=124)),
                ('phone', models.CharField(max_length=11)),
                ('user_role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_value', models.IntegerField()),
            ],
            options={
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='SummaryBulletin',
            fields=[
                ('bulletin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.bulletin')),
            ],
            options={
                'db_table': 'summary_bulletin',
            },
            bases=('db_generate_app.bulletin',),
        ),
        migrations.CreateModel(
            name='ActivityConfirmedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('proofPicture', models.CharField(max_length=255)),
                ('censor_state', models.CharField(max_length=50)),
                ('activity_registry', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_generate_app.activityregistry')),
            ],
            options={
                'db_table': 'activity_confirmed_attendance',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.interaction')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comment',
            },
            bases=('db_generate_app.interaction',),
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.interaction')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reactions',
            },
            bases=('db_generate_app.interaction',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.user')),
                ('achievement', models.CharField(max_length=50)),
                ('mssv', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'student',
            },
            bases=('db_generate_app.user',),
        ),
        migrations.CreateModel(
            name='StudentAffairsOfficer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.user')),
            ],
            options={
                'db_table': 'student_affairs_officer',
            },
            bases=('db_generate_app.user',),
        ),
        migrations.CreateModel(
            name='StudentAssistant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.user')),
            ],
            options={
                'db_table': 'student_assistant',
            },
            bases=('db_generate_app.user',),
        ),
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bonus_score', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.semester')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.term')),
                ('student_assistant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.studentassistant')),
            ],
            options={
                'db_table': 'extra_activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityBulletin',
            fields=[
                ('bulletin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.bulletin')),
                ('extra_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.extraactivity')),
            ],
            options={
                'db_table': 'activity_bulletin',
            },
            bases=('db_generate_app.bulletin',),
        ),
        migrations.CreateModel(
            name='CancelActivityRequirement',
            fields=[
                ('cancelrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.cancelrequirement')),
                ('extra_activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.extraactivity')),
            ],
            options={
                'db_table': 'cancel_activity_requirement',
            },
            bases=('db_generate_app.cancelrequirement',),
        ),
        migrations.CreateModel(
            name='CancelBulletinRequirement',
            fields=[
                ('cancelrequirement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db_generate_app.cancelrequirement')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.bulletin')),
            ],
            options={
                'db_table': 'cancel_bulletin_requirement',
            },
            bases=('db_generate_app.cancelrequirement',),
        ),
        migrations.AddField(
            model_name='interaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_generate_app.student'),
        ),
        migrations.AddField(
            model_name='activityregistry',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.student'),
        ),
        migrations.AddField(
            model_name='cancelrequirement',
            name='student_affairs_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.studentaffairsofficer'),
        ),
        migrations.CreateModel(
            name='MissingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('proof_content', models.TextField(null=True)),
                ('proof_picture', models.CharField(max_length=255, null=True)),
                ('executed_status', models.CharField(max_length=50)),
                ('extra_activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.extraactivity')),
                ('missing_activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_generate_app.activityconfirmedattendance')),
                ('summary_bulletin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.summarybulletin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.student')),
                ('student_assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db_generate_app.studentassistant')),
            ],
            options={
                'db_table': 'missing_activity',
            },
        ),
    ]
